<nav class="nav nav-tabs" id="navigace" role="tablist" >

  <!-- záložka O aplikaci -->
    <a class="nav-item nav-link" id="o-aplikaci-tab" data-toggle="tab" href="#o-aplikaci" role="tab"
        aria-controls="o-aplikaci" aria-selected="false" >O aplikaci</a>

  <!-- záložka Pojištěnci -->
    <a class="nav-item nav-link active" id="pojistenci-tab" data-toggle="tab" href="#pojistenci" role="tab"
        aria-controls="pojistenci" aria-selected="true" >Pojištěnci</a>
  
  <!-- záložka Pojištění  
    <a class="nav-item nav-link disabled" id="pojisteni-tab" data-toggle="tab" href="#pojisteni" role="tab"
        aria-controls="pojisteni" aria-selected="true" >Pojištění</a>
  -->
  
 <!-- záložka Autor -->
 <a class="nav-item nav-link" id="autor-tab" data-toggle="tab" href="#autor" role="tab"
        aria-controls="autor" aria-selected="true" >Autor</a>
 


 </nav>
