
 <div id="oaplikaciStyl" class="flex justify-content-center mx-2 mt-2">   
     <h4 class="h4">Evidence pojištění - Zjednodušená verze</h4>   
        <ul class="list-unstyled m-0 p-0">
            <li class="m-0">Aplikace obsahuje správu <strong class="h6">Pojištěnců</strong>
                <ul class="m-0">
                    <li class="m-0">Vytvoření nového pojištěnce
                            <ul class="m-0">
                                <dt class="m-0 font-weight-bold small">Titul
                                    <dd class="m-0"><small class="m-0 text-muted">-->>Je zde možnost výběru titulů<<--</small> </dd>
                                </dt>
                                <dt class="m-0 font-weight-bold small">Jméno</dt>
                                <dt class="m-0 font-weight-bold small">Příjmení</dt>
                                <dt class="m-0 font-weight-bold small">Narození</dt>
                                 <dd class="m-0"><small class="m-0 text-muted">-->>Je zde možnost výběru s kalendáře [20.08.1978]<<--</small></dd>    
                                </dt>
                                <dt class="m-0 font-weight-bold small">Ulice</dt>
                                <dt class="m-0 font-weight-bold small">Město</dt>
                                <dt class="m-0 font-weight-bold small">PSČ</dt>
                                 <dd class="m-0"><small class="m-0 text-muted">-->>Při psaní je vložena mezera [276 01]<<-</small></dd>    
                                </dt>
                                <dt class="m-0 font-weight-bold small">Telefon
                                 <dd class="m-0"><small class="m-0 text-muted">-->>Při psaní jsou vloženy mezery [705 806 588]<<-</small></dd>    
                                </dt>
                            </ul>
                    </li>
                    <li class="m-0">Zobrazení seznamu všech pojištěných</li>
                        <ul class="m-0">
                                <dt class="m-0 font-weight-bold small">Tlačitko vymaž aktuální záznam
                                    <dd class="m-0"><small class="m-0 text-muted small">-->>Vymaže aktuálního pojištěnce<<-- <small class="text-danger"></small></small> </dd>
                                </dt>
                                <dt class="m-0 font-weight-bold small">Tlačitko edituj aktuální záznam
                                    <dd class="m-0"><small class="m-0 text-muted small">-->>Edituje aktuálního pojištěnce<<-- <small class="text-danger"></small></small> </dd>
                                </dt>
                        </ul>                
                </ul>
            </li>
        </ul>
 </div>   
