<div class="outer-container">
    <div class="inner-container">
        <div class="centered-content">
            <div id="logo">
                <h1>Radek<span>Jindra</span></h1>
                <a id="odkazWebAutora" href="http://jindrovi.cz/">www.jindrovi.cz</a>
                <a id="odkazEmailAutora" href="mailto:radek@jindrovi.cz">Email</a>
                <a id="odkazLinkedinAutora" href="https://www.linkedin.com/in/radek-jindra-806233178/">LinkedIn</a>
            </div>
        </div>
    </div>
</div>