<div id="paticka" class="fixed-bottom bg-dark text-light m-0 p-0 small">
  Vytvořil ©
  <a id="jindrovi" class="m-0 p-0" href="http://www.jindrovi.cz" title="www.jindrovi.cz">Radek JINDRA</a>
  podle školení na
  <a id="itnetwork" class="m-0 p-0" href="http://www.itnetwork.cz" title="www.itnetwork.cz"><strong>IT</strong>network.</a>
  poděkování za informace patří
  <a class="m-0 p-0" href="http://www.itnetwork.cz">
    <img class="p-0 m-0" src="../obrazky/itnetwork.png" width="23" height="23" alt="www.itnetwork.cz" title="www.itnetwork.cz">
  </a>
  <a class="m-0 p-0" href="http://www.stackoverflow.com">
    <img class="p-0 m-0" src="../obrazky/stackOverflow.png" width="23" height="23" alt="www.stackoverflow.com" title="www.stackoverflow.com">
  </a>
  <a class="m-0 p-0" href="https://getbootstrap.com/docs/4.0/">
    <img class="p-0 m-0" src="../obrazky/bootstrap.svg" width="23" height="23" alt="www.getbootstrap.com" title="www.getbootstrap.com">
  </a>
  <a class="m-0 p-0" href="http://www.google.com">
    <img class="p-0 m-0" src="../obrazky/google.png" width="23" height="23" alt="www.google.com" title="www.google.com">
  </a>
  <a class="m-0 p-0" href="http://www.chrome.com">
    <img class="p-0 m-0" src="../obrazky/chrome.jpg" width="23" height="23" alt="www.chrome.com" title="www.chrome.com">
  </a>
  <a class="m-0 p-0" href="http://www.php.net">
    <img class="p-0 m-0" src="../obrazky/php.png" width="23" height="23" alt="www.php.net" title="www.php.net">
  </a>
  <a class="m-0 p-0" href="http://php.vrana.cz">
    <img class="p-0 m-0" src="../obrazky/vrana.jpg" width="23" height="23" alt="www.vrana.cz" title="www.vrana.cz">
  </a>
  
</div>