<!-- bootstrap -->
<link rel="stylesheet" href="../css/bootstrap.min.css">
<script src="../js/jquery-3.2.1.slim.min.js"></script>
<script src="../js/popper.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
<script src="../js/bootstrap.bundle.min.js"></script>
<script src="../js/bootstrap-confirmation.min.js"></script>
<script src="../js/jquery.js"></script>
<script src="../js/popper.js"></script>



<!-- vlastní css -->
<link rel="stylesheet" href="../css/styl.css" type="text/css"/>
<!-- vlastnosti tabulky a formulaře Uživatele -->
<link rel="stylesheet" href="../css/pozice-tabulky.css" type="text/css" />
<!-- script na přidání mezery do PSČ -->
<script src="../js/mezera_PSC.js"></script>
<!-- script na přidání mezery do telefonu -->
<script src="../js/mezery_telefon.js"></script>
<!-- script na validaci formuláře -->
<script src="../js/validace_formulare.js"></script>
<!-- script na refresh tabulky -->
<script src="../js/refresh_tabulky_pojistence.js"></script>
<!-- vyvolání modálních oken -->
<script src="../js/modalni_okna.js"></script>
<!-- práce s kartamy v bootstrapu -->
<script src="../js/bootstrap-karty.js"></script>







  
  
  
