<datalist id='listTypPojisteni'>
    <!-- Životní pojištění -->
    <option label="Pojištění osob   :">Životní pojištění</option>
    <option label="Pojištění osob   :">Úrazové pojištění</option>
    <!-- Majetkové pojištění -->
    <option label="Pojištění majetku:">Autopojištění</option>
    <option label="Pojištění majetku:">Nemovitosti</option>
    <option label="Pojištění majetku:">Cestovní pojištění odpovědnosti</option>
    <option label="Pojištění majetku:">Podnikatelská pojišťovna</option>
    <!-- Penzijní produkty -->
    <option label="Penzijní produkty:">Transformovaný fond</option>
    <option label="Penzijní produkty:">DPS</option>
    <!-- Investice -->
    <option label="">Investice</option>
    <!-- Stavební spoření -->
    <option label="">Stavební spoření</option>
    <!-- Hypotéky a úvěry -->
    <option label="">Hypotéky a úvěry</option>
</datalist>
